apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-frontend
  labels:
    app: node-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-frontend
  template:
    metadata:
      labels:
        app: node-frontend
    spec:
      containers:
      - name: node-frontend-deployment
        image: bigleu007/frontend:v2
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8081
        env:
        - name: FLASK_BACKEND_URL
          value: "http://flask-backend-service:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: node-frontend-service
spec:
  selector:
    app: node-frontend
  type: LoadBalancer
  ports:
   - protocol: TCP 
     port: 8081
     targetPort: 8081
     nodePort: 30000

