apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: bigleu007/backend:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
spec:
  selector:
    app: flask-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-frontend
  template:
    metadata:
      labels:
        app: nodejs-frontend
    spec:
      containers:
      - name: nodejs-frontend
        image: bigleu007/frontend:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: FLASK_BACKEND_URL
          value: "http://flask-backend-service:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-frontend-service
spec:
  selector:
    app: nodejs-frontend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
spec:
  selector:
    app: nodejs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30000
  type: NodePort
