"""Description of migration

Revision ID: 0d0df91e2bf9
Revises: 81dd5378d9af
Create Date: 2024-05-16 10:08:40.506879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0df91e2bf9'
down_revision: Union[str, None] = '81dd5378d9af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mymodel', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mymodel', 'age')
    # ### end Alembic commands ###
