"""Description of migration

Revision ID: 1580689dec02
Revises: cb35603f8ce2
Create Date: 2024-05-16 10:08:19.015562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1580689dec02'
down_revision: Union[str, None] = 'cb35603f8ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mymodel', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mymodel', sa.Column('age', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
