"""Description of migration

Revision ID: 16c77c1a46a5
Revises: 0d0df91e2bf9
Create Date: 2024-05-16 10:08:43.402540

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16c77c1a46a5"
down_revision: Union[str, None] = "0d0df91e2bf9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
