"""Description of migration

Revision ID: 34083eff4622
Revises: 2a91848afcb0
Create Date: 2024-05-16 10:02:26.447989

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34083eff4622"
down_revision: Union[str, None] = "2a91848afcb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mymodel", sa.Column("sex", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mymodel", "sex")
    # ### end Alembic commands ###
