"""Description of migration

Revision ID: e1b566216eb3
Revises: 12390145e2af
Create Date: 2024-05-16 10:03:55.917471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b566216eb3'
down_revision: Union[str, None] = '12390145e2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mymodel', 'sex')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mymodel', sa.Column('sex', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
